name: Library Management App Build

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12
  MONGO_URI: mongodb://localhost:27017  # Set this to your local MongoDB URI or MongoDB Atlas URI

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Set Environment Variables
      run: |
        echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV

    - name: Install MongoDB
      run: |
        choco install mongodb --version=4.4.6
        # Check if MongoDB service is running, if not, start it
        if (-not (Get-Service MongoDB -ErrorAction SilentlyContinue)) {
          net start MongoDB
        } else {
          Write-Host "MongoDB service is already running."
        }

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask
        pip install pymongo

    - name: Run Flask App
      run: |
        python "V3 Komplete/app.py"  # Running the app.py to start the Flask server
      env:
        FLASK_APP: "V3 Komplete/app.py"
        FLASK_ENV: "development"
