name: Library Management App Build

on:
  # Runs on push to main or master branch
  push:
    branches:
      - main
      - master
  # Runs on pull request events targeting main or master branch
  pull_request:
    branches:
      - main
      - master

  # Allows manual triggering of the workflow
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Set Environment Variables
      run: |
        echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pymongo
        pip install flask

    - name: Run Tests
      run: |
        # Replace with your test command or script
        python -m unittest discover -s tests

    - name: Package Application
      run: |
        # Use PyInstaller to create an executable (adjust if needed)
        pip install pyinstaller
        pyinstaller --onefile app.py

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: library-management-build
        path: dist/
        if-no-files-found: error
        overwrite: false
