name: Library Management App Build

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12
  MONGO_URI: mongodb://localhost:27017  # Set this to your local MongoDB URI or MongoDB Atlas URI

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Set Environment Variables
      run: |
        echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV

    - name: Install MongoDB
      run: |
        choco install mongodb --version=4.4.6
        # Check if MongoDB service is running, if not, start it
        if (-not (Get-Service MongoDB -ErrorAction SilentlyContinue)) {
          net start MongoDB
        } else {
          Write-Host "MongoDB service is already running."
        }

    - name: Install Ngrok
      run: |
        choco install ngrok

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask
        pip install pymongo

    - name: Start Ngrok Tunnel
      run: |
        ngrok http 5000 > ngrok.log &  # Start ngrok and redirect logs to a file

    - name: Wait for Ngrok to initialize
      run: |
        # Wait for Ngrok to establish the tunnel and log the URL
        Start-Sleep -Seconds 10
        # Display the last 10 lines of ngrok.log to get the public URL
        Get-Content ngrok.log -Tail 10

    - name: Verify Ngrok Tunnel
      run: |
        curl http://localhost:4040/api/tunnels  # Ngrok provides an API to check the tunnel status

    - name: Display Ngrok Log
      run: |
        Get-Content ngrok.log -Tail 20  # Display the last 20 lines of the ngrok log to check for URL details

    - name: Run Flask App
      run: |
        python "V3 Komplete/app.py"  # Running the app.py to start the Flask server
      env:
        FLASK_APP: "V3 Komplete/app.py"
        FLASK_ENV: "development"
