name: Library Management App Build

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Set Environment Variables
      run: |
        echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV

    - name: Install Dependencies and pyinstaller
      run: |
        python -m pip install --upgrade pip
        pip install pymongo 
        pip install flask
        pip install pyinstaller
        pip show pyinstaller  # To verify that pyinstaller was installed

    - name: Run Tests
      run: |
        if (Test-Path tests) {
          python -m unittest discover -s tests
        } else {
          Write-Host "No tests found. Skipping test step."
        }
      shell: pwsh

    - name: List files before building
      run: |
        dir "V3 Komplete"

    - name: Package Application
      run: |
        cd "V3 Komplete"  # Change to the correct directory
        pyinstaller --onefile --debug app.py

    - name: List contents of dist directory
      run: |
        dir dist

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: library-management-build
        path: dist/*   # Upload everything inside dist/
        if-no-files-found: error
        overwrite: false
