name: Library Management App Build

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Debug file structure
      run: ls -R

    - name: Install Dependencies
      run: |
        if [ -f requirements.txt ]; then
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        else
          echo "requirements.txt not found. Skipping dependency installation."
        fi

    - name: Run Tests
      run: |
        python -m unittest discover -s tests || echo "No tests found, skipping."

    - name: Package Application
      run: |
        pip install pyinstaller
        pyinstaller --onefile app.py

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: library-management-build
        path: dist/
        if-no-files-found: error
        overwrite: false
